
pipeline:
  integration-tests:
    image: python:3.6
    commands:
      - "python -m venv .venv"
      - "./run-masabot.sh &"
      - "sleep 20"
      - ". .venv/bin/activate"
      - "python -m unittest discover -s tests/integration -p \"*_test.py\""
      - "pkill -P $$"
    when:
      event: [pull_request, push]
      branch: master

